// examples/vue/src/components/Widget.vue
<template>
  <Widget :config="config" />
</template>

<script lang="ts">
import { applyPureReactInVue } from 'veaury';
// This is a React component
import { LiFiWidget } from '@collabland/lifi-widget';

export default {
  components: {
    // Use HOC 'applyReactInVue' or 'applyPureReactInVue'
    // Basic: applyReactInVue(LiFiWidget),
    Widget: applyPureReactInVue(LiFiWidget)
  },
  setup() {
    return {
      config: {
        containerStyle: {
          border: `1px solid rgb(234, 234, 234)`,
          borderRadius: '16px',
        },
        integrator: 'vue-example'
      },
    }
  }
}
</script>

// examples/nextjs14/app/widget.tsx
'use client';
import { LiFiWidget } from '@collabland/lifi-widget';
import { useEffect, useState } from 'react';

export function Widget() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  return (
    <main>
      {mounted && (
        <LiFiWidget
          config={{
            containerStyle: {
              border: `1px solid rgb(234, 234, 234)`,
              borderRadius: '16px',
            },
          }}
          integrator="li.fi-playground"
        />
      )}
    </main>
  );
}
